# Importation des modules nécessaires

In [1]:
from Extract.API import API
from Extract.Scrapping import Scrapping
from Transform.TransformData import TransformData
import pandas as pd

# Récupération de la donnée (via api)

In [2]:
# Utiliser l'API pour récupérer les données vélo/piéton
api = API()

# Lien de l'API qui retourne un CSV
lien_api_velo_pieton = (
    "https://data.rennesmetropole.fr/api/explore/v2.1/catalog/datasets/"
    "eco-counter-data/exports/csv?lang=fr&timezone=Europe%2FBerlin&"
    "use_labels=true&delimiter=%3B"
)

# Récupérer toutes les données au format CSV
csv_pieton_velo_rennes = api.get_api_data(lien_api_velo_pieton)

# Vérifier et afficher les données récupérées
if csv_pieton_velo_rennes is not None:
    print(f"Total d'enregistrements récupérés : {len(csv_pieton_velo_rennes)}")
else:
    print("Aucune donnée récupérée.")

df = pd.DataFrame(csv_pieton_velo_rennes)
df.head()

Les données ont été chargées avec succès.
Total d'enregistrements récupérés : 137218

,date,isoDate,counts,status,ID,name,counter,geo,sens
0,2015-12-27T19:00:00+01:00,2015-12-27T18:00:00+0100,5.0,0.0,100017942,Boulevard Georges Pompidou,NaN,"48.1014223209623, -1.68490237617492",5
1,2015-12-28T04:00:00+01:00,2015-12-28T03:00:00+0100,1.0,0.0,100017942,Boulevard Georges Pompidou,NaN,"48.1014223209623, -1.68490237617492",5
2,2015-12-28T13:00:00+01:00,2015-12-28T12:00:00+0100,8.0,0.0,100017942,Boulevard Georges Pompidou,NaN,"48.1014223209623, -1.68490237617492",5
3,2015-12-28T18:00:00+01:00,2015-12-28T17:00:00+0100,16.0,0.0,100017942,Boulevard Georges Pompidou,NaN,"48.1014223209623, -1.68490237617492",5
4,2015-12-28T22:00:00+01:00,2015-12-28T21:00:00+0100,2.0,0.0,100017942,Boulevard Georges Pompidou,NaN,"48.1014223209623, -1.68490237617492",5

# Récupération de la data (via scrapping)

# Transformation de la data

In [9]:
scrap = Scrapping()
col, data = scrap.scrap_site()
df = pd.DataFrame(data, columns=col)
df.head(11)

,Heure locale\naccess_time\n30mn\nMETAR,,Température,Temps,Pluie,Vent,Humidité,Bio-météo,Pt. de rosée,Pression,Visibilité,Date
0,09h,add_circle_outline,6.3 °C\n3.9 → 6.3,,0 mm/1h,11 km/h\nraf.16.6,94%,4\n\n22,5.4 °C,1033.1hPa,19 km,12/11/2024
1,08h,add_circle_outline,4.0 °C\n3.8 → 5.2,,0 mm/1h,11 km/h\nraf.14.4,97%,1.3,3.6 °C,1033.3hPa,17 km,12/11/2024
2,07h,add_circle_outline,5.1 °C\n5 → 5.4,,0 mm/1h,11 km/h\nraf.12.6,96%,2.6,4.5 °C,1033.6hPa,19 km,12/11/2024
3,06h,add_circle_outline,5.3 °C\n5.2 → 5.6,,0 mm/1h,11 km/h\nraf.12.6,96%,2.8,4.7 °C,1034.1hPa,24 km,12/11/2024
4,05h,add_circle_outline,5.6 °C\n4.8 → 5.6,,0 mm/1h,11 km/h\nraf.13,98%,3.2,5.3 °C,1034.4hPa,12 km,12/11/2024
5,04h,add_circle_outline,5.5 °C\n5.5 → 5.9,,0 mm/1h,7 km/h\nraf.10.4,99%,3.9,5.4 °C,1034.5hPa,5 km,12/11/2024
6,03h,add_circle_outline,5.8 °C\n5 → 6.1,,0 mm/1h,7 km/h\nraf.13.7,100%,4.2,5.8 °C,1034.9hPa,5 km,12/11/2024
7,02h,add_circle_outline,6.0 °C\n6 → 6.5,,0 mm/1h,7 km/h\nraf.12.2,99%,4.5,5.9 °C,1034.9hPa,17 km,12/11/2024
8,01h,add_circle_outline,6.6 °C\n6.2 → 6.8,,0 mm/1h,11 km/h\nraf.11.5,100%,4.4,6.6 °C,1035.1hPa,10 km,12/11/2024
9,00h,add_circle_outline,6.3 °C\n6.1 → 7.5,,0 mm/1h,4 km/h\nraf.8.3,99%,6.1,6.2 °C,1035.7hPa,600 m,11/11/2024
10,23h,add_circle_outline,7.4 °C\n7.3 → 7.9,,0 mm/1h,7 km/h\nraf.12.2,98%,6.1,7.1 °C,1035.7hPa\n\n=,11 km,11/11/2024

In [11]:
transform = TransformData()

df = transform.rename_column(df, 'Heure locale\naccess_time\n30mn\nMETAR', 'Heure_locale')
df = transform.remove_currency_symbols(df, ['Heure_locale', 'Humidité', 'Pression', 'Visibilité', 'Température', 'Pluie', 'Vent', 'Pt. de rosée'])
df = transform.rename_column(df, 'Température', 'Température (°C)')
df = transform.rename_column(df, 'Pluie', 'Pluie (mm/h)')
df = transform.rename_column(df, 'Humidité', 'Humidité (%)')
df = transform.rename_column(df, 'Pt. de rosée', 'Point_rosé (°C)')
df = transform.rename_column(df, 'Pression', 'Pression (hPa)')
df = transform.rename_column(df, 'Visibilité', 'Visibilité (km)')
df = transform.rename_column(df, 'Vent', 'Vent (km/h)')
df = transform.remove_column(df, ['', 'Temps', 'Bio-météo'])

df.head()

Traitement de la colonne: Heure_locale
Traitement de la colonne: Humidité
Traitement de la colonne: Pression
Traitement de la colonne: Visibilité
Traitement de la colonne: Température
Traitement de la colonne: Pluie
Traitement de la colonne: Vent
Traitement de la colonne: Pt. de rosée

,Heure_locale,Température (°C),Pluie (mm/h),Vent,Humidité (%),Point_rosé (°C),Pression (hPa),Visibilité (km),Date
0,09,6.3,0,11,94,5.4,1033.1,19,12/11/2024
1,08,4.0,0,11,97,3.6,1033.3,17,12/11/2024
2,07,5.1,0,11,96,4.5,1033.6,19,12/11/2024
3,06,5.3,0,11,96,4.7,1034.1,24,12/11/2024
4,05,5.6,0,11,98,5.3,1034.4,12,12/11/2024